# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'magic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for magic

  target 'magicTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'magicUITests' do
    # Pods for testing
  end

pod 'AFNetworking', '~> 3.0'
pod 'Kingfisher', '~> 4.0'
end

